name: Build Windows 

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            diffutils 
            git 
            m4 
            make 
            patch 
            tar 
            p7zip 
            curl 
            python
            wget
            cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain

      - name: Prepare build directory
        shell: msys2 {0}
        run: |
          mkdir -p /home/build
          cd /home/build
          echo "Now in: $(pwd)"

      - name: Clone Julia repository
        shell: msys2 {0}
        run: |
          cd /home/build
          git clone https://github.com/JuliaLang/julia.git julia

      - name: Patch Python -c quoting issue
        shell: msys2 {0}
        run: |
          find /home/build/julia -type f -exec sed -i 's|python -c \(from __future__.*print(platform.system())\)|python -c "\1"|' {} +

      - name: Use custom CI Makefile
        shell: msys2 {0}
        run: |
          cp /home/build/Makefile.ci /home/build/julia/Makefile

      - name: Build Julia
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
          PATH: /mingw64/bin:/usr/bin:/bin
        run: |
          cd /home/build/julia
          echo "Starting build in: $(pwd)"
          which mingw32-make
          which gcc
          mingw32-make -j$(nproc)
          echo "Build complete. Julia executable should be at usr/bin/julia.exe"
