name: Build Julia and Create Release

on:
  workflow_dispatch:
    inputs:
      julia_version:
        description: 'Julia version to build (e.g., v1.11.6)'
        required: true
        default: 'v1.11.6'

jobs:
  build-julia:
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 for Julia build
        uses: elan8/setup-msys2-julia@v0.0.2
        with:
          update: false
          install: >-
            base-devel
            diffutils
            git
            m4
            make
            patch
            tar
            p7zip
            curl
            python
            wget
            cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain

      - name: Build Julia
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
          USE_GPL_LIBS: 0
          USE_BINARYBUILDER: 1
        run: |
          echo "Cloning Julia repository:"
          git clone https://github.com/JuliaLang/julia.git
          cd julia
          git checkout ${{ github.event.inputs.julia_version }}
          
          echo "Removing SparseArrays completely for GPL-free build:"
          # Remove SparseArrays from the INDEPENDENT_STDLIBS list in stdlib.mk
          sed -i 's/SparseArrays //g' stdlib/stdlib.mk
          
          # Remove SparseArrays from stdlib/Project.toml
          sed -i '/SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"/d' stdlib/Project.toml
          
          # Remove SparseArrays from Random's test dependencies
          sed -i 's/SparseArrays, //g' stdlib/Random/Project.toml
          sed -i 's/, SparseArrays//g' stdlib/Random/Project.toml
          
          # Remove SparseArrays from Future's test dependencies  
          sed -i 's/SparseArrays, //g' stdlib/Future/Project.toml
          sed -i 's/, SparseArrays//g' stdlib/Future/Project.toml
          
          # Remove SparseArrays from stdlib/Manifest.toml
          sed -i '/^\[\[deps\.SparseArrays\]\]/,/^$/d' stdlib/Manifest.toml
          
          # Remove SparseArrays weak dependency and extension from Statistics in Manifest.toml
          sed -i '/weakdeps = \["SparseArrays"\]/d' stdlib/Manifest.toml
          sed -i '/SparseArraysExt = \["SparseArrays"\]/d' stdlib/Manifest.toml
          sed -i '/\[deps\.Statistics\.extensions\]/d' stdlib/Manifest.toml
          
          # Remove SparseArrays from test files
          sed -i 's/using Test, SparseArrays/using Test/g' stdlib/Random/test/runtests.jl
          # Fix the ambiguous.jl file - properly remove SparseArrays from the filter condition
          sed -i 's/x != "LinearAlgebra" && x != "SparseArrays" &&/x != "LinearAlgebra" &&/g' test/ambiguous.jl
          
          # Remove SparseArrays from documentation
          sed -i 's/SparseArrays, //g' doc/make.jl
          sed -i 's/using SparseArrays, LinearAlgebra/using LinearAlgebra/g' doc/make.jl
          
          # Modify precompile test to be more lenient for GPL-free builds
          sed -i 's/@test length(targets) > 1/@test length(targets) >= 1/g' test/precompile.jl
          
          echo "Starting GPL free Julia build in: $(pwd)"
          make -j$(nproc)
          echo "Build complete. Julia executable should be at usr/bin/julia.exe"

      - name: Upload Julia build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: julia-windows-x86_64
          path: julia/

      - name: Compress Julia build folder
        run: |
          powershell -Command "Compress-Archive -Path julia/* -DestinationPath julia-windows-x86_64.zip"

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.julia_version }}
          name: Julia ${{ github.event.inputs.julia_version }} (GPL-free)
          body: |
            GPL-free Julia build for Windows x86_64
            
            This build excludes SparseArrays and other GPL-licensed components.
            Built with USE_GPL_LIBS=0 and USE_BINARYBUILDER=1.
          draft: false
          prerelease: false
          files: julia-windows-x86_64.zip 