name: Build Windows (Official Method)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            diffutils 
            git 
            m4 
            make 
            patch 
            tar 
            p7zip 
            curl 
            python
            wget
            cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain

      - name: Downgrade GCC and CRT to compatible versions
        shell: msys2 {0}
        run: |
          curl -LO https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-crt-10.0.0-1-any.pkg.tar.zst
          curl -LO https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-12.2.0-3-any.pkg.tar.zst
          pacman -U --noconfirm mingw-w64-x86_64-crt-10.0.0-1-any.pkg.tar.zst mingw-w64-x86_64-gcc-12.2.0-3-any.pkg.tar.zst


      - name: Clone Julia Repository
        run: |
          git clone https://github.com/JuliaLang/julia.git


      - name: Build Julia
        shell: msys2 {0}
        run: |
          cd julia
          echo "Starting build in: $(pwd)"
          make -j$(nproc)
          echo "Build complete. Julia executable should be at usr/bin/julia.exe"
