name: Build Windows 

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            diffutils 
            git 
            m4 
            make 
            patch 
            tar 
            p7zip 
            curl 
            python
            wget
            cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain

      - name: Build Julia
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
        run: |
          echo "Cloning Julia repository:"
          git clone https://github.com/JuliaLang/julia.git
          cd julia
          echo "Starting build in: $(pwd)"
          make -j$(nproc)
          echo "Build complete. Julia executable should be at usr/bin/julia.exe"

      - name: Upload Julia build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: julia-windows-x86_64
          path: julia/

