name: Build Windows 

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2 for Julia build
        uses: elan8/setup-msys2-julia@v0.0.2
        with:
          update: false
          install: >-
            base-devel
            diffutils 
            git 
            m4 
            make 
            patch 
            tar 
            p7zip 
            curl 
            python
            wget
            cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain

      - name: Build Julia
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
          USE_GPL_LIBS: 0
          USE_BINARYBUILDER: 1
        run: |
          echo "Cloning Julia repository:"
          git clone https://github.com/JuliaLang/julia.git
          cd julia
          git checkout v1.11.6
          
          echo "Removing SparseArrays completely for GPL-free build:"
          # Remove SparseArrays from the INDEPENDENT_STDLIBS list in stdlib.mk
          sed -i 's/SparseArrays //g' stdlib/stdlib.mk
          
          # Remove SparseArrays from stdlib/Project.toml
          sed -i '/SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"/d' stdlib/Project.toml
          
          # Remove SparseArrays from Random's test dependencies
          sed -i 's/SparseArrays, //g' stdlib/Random/Project.toml
          sed -i 's/, SparseArrays//g' stdlib/Random/Project.toml
          
          # Remove SparseArrays from Future's test dependencies  
          sed -i 's/SparseArrays, //g' stdlib/Future/Project.toml
          sed -i 's/, SparseArrays//g' stdlib/Future/Project.toml
          
          echo "Starting GPL free Julia build in: $(pwd)"
          make -j$(nproc)
          echo "Build complete. Julia executable should be at usr/bin/julia.exe"

      - name: Upload Julia build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: julia-windows-x86_64
          path: julia/

