name: Build Windows

on:
  workflow_dispatch:

jobs:
  quick-build:
    runs-on: windows-latest

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            cmake 
            diffutils 
            git 
            m4 
            make 
            patch 
            tar 
            p7zip 
            curl 
            python
            mingw-w64-x86_64-gcc 


      - name: Build Julia 
        shell: msys2 {0}
        run: |
          echo "Testing Python execution:"
          python -c 'import platform; print(platform.system())'

          echo "Cloning Julia repository:"
          mkdir -p /c/julia
          cd /c/julia
          git clone --depth 1 --branch v1.11.6 https://github.com/JuliaLang/julia.git src
          cd src

          echo "Starting build in: $(pwd)"
          make

